<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKtyqfpa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKtyqfpa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKtyqfpa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKtyqfpa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKtyqfpa\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ktyqfpa',
    'container.build_id' => '3bc1950f',
    'container.build_time' => 1606932993,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKtyqfpa');
